version: "3"
services:
  pubsub:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - 8000:80

  sfu:
    image: public.ecr.aws/c4s9i0a6/ion-server:latest
    volumes:
      - ../../config.toml:/configs/sfu.toml
    ports:
      - "5000-5200:5000-5200/udp"
      - 7000:7000
