version: "3"
services:
  pubsub:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - 8000:80

  sfu:
    image: 949696328322.dkr.ecr.eu-central-1.amazonaws.com/ion-server:latest
    ports:
      - "5000-5200:5000-5200/udp"
      - 7000:7000
