name: build json-rpc
on:
  push:
    branches:
    - updates
  pull_request:
    branches:
    - updates
jobs:
  deploy:
    name: build json-rpc
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download File from S3
      uses: docker://amazon/aws-cli:2.0.7
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        docker build -t ion-server -f ./cmd/signal/json-rpc/Dockerfile .
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/c4s9i0a6
        docker tag ion-server:latest public.ecr.aws/c4s9i0a6/ion-server:latest
        docker push public.ecr.aws/c4s9i0a6/ion-server:latest

